# Generated by Django 3.2.9 on 2021-12-01 06:40

import apps.base.model_sharding
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log2020',
                'verbose_name_plural': 'Log2020',
                'db_table': 'demo_log_2020',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='Log2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log2021',
                'verbose_name_plural': 'Log2021',
                'db_table': 'demo_log_2021',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User0',
                'verbose_name_plural': 'User0',
                'db_table': 'demo_user_0',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User1',
                'verbose_name_plural': 'User1',
                'db_table': 'demo_user_1',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User2',
                'verbose_name_plural': 'User2',
                'db_table': 'demo_user_2',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User3',
                'verbose_name_plural': 'User3',
                'db_table': 'demo_user_3',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User4',
                'verbose_name_plural': 'User4',
                'db_table': 'demo_user_4',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User5',
                'verbose_name_plural': 'User5',
                'db_table': 'demo_user_5',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User6',
                'verbose_name_plural': 'User6',
                'db_table': 'demo_user_6',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User7',
                'verbose_name_plural': 'User7',
                'db_table': 'demo_user_7',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User8',
                'verbose_name_plural': 'User8',
                'db_table': 'demo_user_8',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
        migrations.CreateModel(
            name='User9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User9',
                'verbose_name_plural': 'User9',
                'db_table': 'demo_user_9',
            },
            bases=(models.Model, apps.base.model_sharding.ShardingMixin),
        ),
    ]
