# Generated by Django 3.2.9 on 2021-12-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log2020',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='is_deleted'),
        ),
        migrations.AddField(
            model_name='log2021',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='is_deleted'),
        ),
    ]
